[tool.poetry]
name = "kartan-generointi"
version = "0.1.0"
description = ""
authors = ["Kassudin <kasper.kinnarinen@live.fi>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
